name = "telegram-echo-bot"
compatibility_date = "2024-03-01"

main = "src/index.js"
workers_dev = true

[[kv_namespaces]]
binding = "KV_BINDING"
id = "KV_ID"
preview_id = "KV_PREVIEW_ID" # Optional (to separate develop and production databases)

[vars]
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
ADMIN_USER_ID = "ADMIN_USER_ID"
TZ = "YOUR_TIMEZONE" # Optional (e.g. "Asia/Tehran" / default: "UTC")

[triggers]
crons = ["0 0 * * *"]  # Daily export

[observability.logs]
enabled = true
